from exceptions.WeoError import WeoError


class OrchestratorError(WeoError):
    pass
